language: go

services: docker

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  fast_finish: true
  include:
    - go: 1.15.x
      env: STABLE=true
    - go: 1.x
    - go: tip
  allow_failures:
    - go: tip

before_install:
  # Install linters
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin ${GOLANGCI_LINT_VERSION}
  - golangci-lint --version
  - curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $GOPATH/bin ${YAEGI_VERSION}
  - go get -u golang.org/x/lint/golint
  # docker part
  - docker run -d --rm --name traefik -p 8080:8080 -p 80:80 -v ${PWD}/:/etc/traefik/ -v /var/run/docker.sock:/var/run/docker.sock:ro traefik
  - docker run -d --rm --link traefik containous/whoami -port 5000 --name service-whoami
  - docker ps -a

install:
  - go mod tidy
  - git diff --exit-code go.mod
  # - git diff --exit-code go.sum
  - go mod download
  - go mod vendor
  # - git diff --exit-code ./vendor/
  - make fmt
  - git diff --exit-code

before_script:
  - make lint test-v

script: ls

after_script:
  - docker run -ti --rm --link traefik --name test alpine apk add curl && curl localhost/whoami
  - curl localhost:5000
  - curl localhost/whoami