language: go

notifications:
  email:
    on_success: never
    on_failure: change

stages:
   - test
   - e2e

cache:
  directories:
    - $GOPATH/pkg/mod

services:
  - docker

jobs:
  fast_finish: true
  include:
    - stage: test
      name: "lint go 1.15.x"
      go: 1.15.x
      env: STABLE=true
      script: make lint test-v
    - stage: test
      name: "lint go 1.x"
      go: 1.x
      script: make lint test-v
    - stage: test
      name: "lint go tip"
      go: tip
      script: make lint test-v
    - stage: e2e
      name: "No-rules"
      go: 1.15.x
      env: STABLE=true
      script: ./ci/scripts/e2e.sh no-rules
      go_import_path: github.com/tommoulard/fail2ban
    - stage: e2e
      name: "Local-banned"
      go: 1.15.x
      env: STABLE=true
      script: ./ci/scripts/e2e.sh local-banned
      go_import_path: github.com/tommoulard/fail2ban
    - stage: e2e
      name: "Local-whited"
      go: 1.15.x
      env: STABLE=true
      script: ./ci/scripts/e2e.sh local-whited
      go_import_path: github.com/tommoulard/fail2ban

  allow_failures:
    - go: tip

before_install:
  # Install linters
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin ${GOLANGCI_LINT_VERSION}
  - golangci-lint --version
  - curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $GOPATH/bin ${YAEGI_VERSION}
  - go get -u golang.org/x/lint/golint

install:
  - go mod tidy
  - git diff --exit-code go.mod
  # - git diff --exit-code go.sum
  - go mod download
  - go mod vendor
  # - git diff --exit-code ./vendor/
  - make fmt
  - git diff --exit-code
